server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:Gautam-A25/digital-supply-chain-config.git
          clone-on-start: true
          default-label: main